[interpolation]
enabled = false
masking = false
type = svp
of blocks = 0
fps = 1920
speed = medium
tuning = weak
algorithm = 23
use gpu = false

[frame blending]
enabled = true
fps = 60
intensity = 1.0
weighting = equal
bright blend = false

# Deprecated to be removed
#   Honestly underwhelming, and it is kinda trash, dont bother using
[flowblur]
enabled = false
masking = false
amount = 125
do blending = after

# Here you can modify FFmpeg arguments, file name, and container
#
# process
#   name of ffmpeg or different implementation with support for ffmpeg commandline arguments.
# 
# enc args
#   Can be any ffmpeg cli argument like:
#     -c:v hevc_nvenc -preset p7 -rc vbr -b:v 250M -cq 20
#   or can be presets defined in encoding_presets.ini like
#     H264_CPU
#
# file format
#   Not implemented yet but refer to https://ctt.cx/video/smoothie/recipe/#output to
#   see how it would work
#
# container
#   video container like .mp4 .webm .mkv etc, as long as the ffmepg build supports it
#   and you have compatible enc args it'd work.
[output]
process = ffmpeg
enc args = H264 CPU
file format = %FILENAME% ~ %FRUIT%
container = .MP4

# Preview of everything before the output stage
[preview window]
enabled = false
process = ffplay
output args = -f yuv4mpegpipe -

# Here you set where your masks exist, and a standard mask where
# a dynamic one cannot be found for you from [dynamic masking]
# 
# feathering
#   Whether you would like to feather your masks.
#
# folder path
#   The folder where your masks exist
#
# file name
#   Standard mask for when a dynamic one cannot be found for you
#
# Example:
#  [artifact masking]
#  enabled = true
#  feathering = true
#  folder path = "C:\Masks"
#  file name = "standard.png"
#  
#  // This would turn into C:\Masks\standard.png
[artifact masking]
enabled = false
feathering = true
folder path = ""
file name = ""

# Assign masks to videos based on parts of video name
# 
# Simplest way to use it:
#   .*cs2.* = "cs2.png"
# here it looks at the video name, and sees if there is "cs2" anywhere,
# and uses the path artifact_masking::folder_path/cs2.png
#
# But since it just uses regex, you can come up with whatever you want,
# if you can use regex or ask ChatGPT to make make one for you.
#
# It works like this:
#   regex = "filename"
[dynamic masking]
enabled = true
# Examples:
#  .*cs2.* = "cs2.png"
#  .*minecraft.* = "minecraft.png"

[miscellaneous]
play ding = false
always verbose = false
dedup threshold = 0.0
global output folder =
source indexing = false
ffmpeg options = -loglevel error -i - -hide_banner -stats -stats_period 0.15
ffplay options = -loglevel quiet -i - -autoexit -window_title smoothie.preview

[timescale]
in = 1.0
out = 1.0

[color grading]
enabled = false
brightness = 1.0
saturation = 1.0
contrast = 1.0

[lut]
enabled = false
path =
opacity = 0.2

[pre-interp]
enabled = false
scene change = false
# Test time augmentation (tta) MASSIVELY(8x) slows down the speed, but is more accurate
tta = false
uhd = false
masking = false
factor = 3x
model = auto

